Restructured Files and updated tools
VSC Has been moved into its own repository for ease of development
Appinfo is being updated to better fit the needs of modern VScript

diff --git a/tools/appinfo b/tools/appinfo
--- a/tools/appinfo
+++ b/tools/appinfo
@@ -1,11 +1,34 @@
 #!/bin/bash
-source $1 --getdata
-echo "Appinfo tool 1.0"
-echo "  App Metadata:"
-echo "  Name: $APP_NAME"
-echo "  Version $APP_VERSION"
-echo "  Name-formatted: $APP_FUZZY_NAME"
-echo "  VScript Data:"
-echo "  VScript Version: $VS_VERSION"
-echo "  VScript Version Codename: $VS_CODENAME"
-echo "  Loaded libraries in runtime: $"
+if [ -f $1 ]
+then
+ 
+ VSCRIPT_APPINFO_NO_EXEC=1 source $1 --getdata
+
+ echo "Appinfo tool 1.1"
+ echo "  App Metadata:"
+ echo "  Name: $APP_NAME"
+ echo "  Version $APP_VERSION"
+ echo "  Display Name: $APP_FUZZY_NAME"
+ if ! [ -z ${COMPILER+x} ]
+ then
+  echo "  Compiler: $COMPILER"
+  COMP=$COMPILER
+ else
+  echo "  Compiler: VRamen? The compiler variable is unset, this indicates vramen, or broken"
+  COMP=vramen
+ fi
+
+ if [ "$COMP" == "vramen" ]
+ then
+  echo "  VScript Data:"
+  echo "   VScript Version: $VS_VERSION"
+  echo "   VScript Version Codename: $VS_CODENAME"
+  echo "   Loaded libraries in runtime: $loadedlibs"
+  echo "   Loaded modules in runtime: $loadedmods"
+ else
+  echo "  "
+ fi
+
+else
+ echo "Error: $1 Does not exist"
+fi
